/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployersDashboardRouteImport } from './routes/employers.dashboard'
import { Route as CompanyRegisterRouteImport } from './routes/company.register'
import { Route as CompanyLoginRouteImport } from './routes/company.login'
import { Route as CandidatesDashboardRouteImport } from './routes/candidates.dashboard'
import { Route as CandidateRegisterRouteImport } from './routes/candidate.register'
import { Route as CandidateLoginRouteImport } from './routes/candidate.login'

const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersDashboardRoute = EmployersDashboardRouteImport.update({
  id: '/employers/dashboard',
  path: '/employers/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRegisterRoute = CompanyRegisterRouteImport.update({
  id: '/company/register',
  path: '/company/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyLoginRoute = CompanyLoginRouteImport.update({
  id: '/company/login',
  path: '/company/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesDashboardRoute = CandidatesDashboardRouteImport.update({
  id: '/candidates/dashboard',
  path: '/candidates/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRegisterRoute = CandidateRegisterRouteImport.update({
  id: '/candidate/register',
  path: '/candidate/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateLoginRoute = CandidateLoginRouteImport.update({
  id: '/candidate/login',
  path: '/candidate/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/register': typeof CandidateRegisterRoute
  '/candidates/dashboard': typeof CandidatesDashboardRoute
  '/company/login': typeof CompanyLoginRoute
  '/company/register': typeof CompanyRegisterRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/register': typeof CandidateRegisterRoute
  '/candidates/dashboard': typeof CandidatesDashboardRoute
  '/company/login': typeof CompanyLoginRoute
  '/company/register': typeof CompanyRegisterRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/register': typeof CandidateRegisterRoute
  '/candidates/dashboard': typeof CandidatesDashboardRoute
  '/company/login': typeof CompanyLoginRoute
  '/company/register': typeof CompanyRegisterRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/candidate/login'
    | '/candidate/register'
    | '/candidates/dashboard'
    | '/company/login'
    | '/company/register'
    | '/employers/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/candidate/login'
    | '/candidate/register'
    | '/candidates/dashboard'
    | '/company/login'
    | '/company/register'
    | '/employers/dashboard'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/candidate/login'
    | '/candidate/register'
    | '/candidates/dashboard'
    | '/company/login'
    | '/company/register'
    | '/employers/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  CandidateLoginRoute: typeof CandidateLoginRoute
  CandidateRegisterRoute: typeof CandidateRegisterRoute
  CandidatesDashboardRoute: typeof CandidatesDashboardRoute
  CompanyLoginRoute: typeof CompanyLoginRoute
  CompanyRegisterRoute: typeof CompanyRegisterRoute
  EmployersDashboardRoute: typeof EmployersDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/dashboard': {
      id: '/employers/dashboard'
      path: '/employers/dashboard'
      fullPath: '/employers/dashboard'
      preLoaderRoute: typeof EmployersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/register': {
      id: '/company/register'
      path: '/company/register'
      fullPath: '/company/register'
      preLoaderRoute: typeof CompanyRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/login': {
      id: '/company/login'
      path: '/company/login'
      fullPath: '/company/login'
      preLoaderRoute: typeof CompanyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/dashboard': {
      id: '/candidates/dashboard'
      path: '/candidates/dashboard'
      fullPath: '/candidates/dashboard'
      preLoaderRoute: typeof CandidatesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/register': {
      id: '/candidate/register'
      path: '/candidate/register'
      fullPath: '/candidate/register'
      preLoaderRoute: typeof CandidateRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/login': {
      id: '/candidate/login'
      path: '/candidate/login'
      fullPath: '/candidate/login'
      preLoaderRoute: typeof CandidateLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  CandidateLoginRoute: CandidateLoginRoute,
  CandidateRegisterRoute: CandidateRegisterRoute,
  CandidatesDashboardRoute: CandidatesDashboardRoute,
  CompanyLoginRoute: CompanyLoginRoute,
  CompanyRegisterRoute: CompanyRegisterRoute,
  EmployersDashboardRoute: EmployersDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
