/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployersDashboardRouteImport } from './routes/employers.dashboard'
import { Route as CandidatesSignupRouteImport } from './routes/candidates.signup'
import { Route as CandidatesSigninRouteImport } from './routes/candidates.signin'
import { Route as CandidatesDashboardRouteImport } from './routes/candidates.dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersDashboardRoute = EmployersDashboardRouteImport.update({
  id: '/employers/dashboard',
  path: '/employers/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesSignupRoute = CandidatesSignupRouteImport.update({
  id: '/candidates/signup',
  path: '/candidates/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesSigninRoute = CandidatesSigninRouteImport.update({
  id: '/candidates/signin',
  path: '/candidates/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesDashboardRoute = CandidatesDashboardRouteImport.update({
  id: '/candidates/dashboard',
  path: '/candidates/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/candidates/dashboard': typeof CandidatesDashboardRoute
  '/candidates/signin': typeof CandidatesSigninRoute
  '/candidates/signup': typeof CandidatesSignupRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/candidates/dashboard': typeof CandidatesDashboardRoute
  '/candidates/signin': typeof CandidatesSigninRoute
  '/candidates/signup': typeof CandidatesSignupRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jobs': typeof JobsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/candidates/dashboard': typeof CandidatesDashboardRoute
  '/candidates/signin': typeof CandidatesSigninRoute
  '/candidates/signup': typeof CandidatesSignupRoute
  '/employers/dashboard': typeof EmployersDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/signin'
    | '/signup'
    | '/candidates/dashboard'
    | '/candidates/signin'
    | '/candidates/signup'
    | '/employers/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jobs'
    | '/signin'
    | '/signup'
    | '/candidates/dashboard'
    | '/candidates/signin'
    | '/candidates/signup'
    | '/employers/dashboard'
  id:
    | '__root__'
    | '/'
    | '/jobs'
    | '/signin'
    | '/signup'
    | '/candidates/dashboard'
    | '/candidates/signin'
    | '/candidates/signup'
    | '/employers/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JobsRoute: typeof JobsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  CandidatesDashboardRoute: typeof CandidatesDashboardRoute
  CandidatesSigninRoute: typeof CandidatesSigninRoute
  CandidatesSignupRoute: typeof CandidatesSignupRoute
  EmployersDashboardRoute: typeof EmployersDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers/dashboard': {
      id: '/employers/dashboard'
      path: '/employers/dashboard'
      fullPath: '/employers/dashboard'
      preLoaderRoute: typeof EmployersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/signup': {
      id: '/candidates/signup'
      path: '/candidates/signup'
      fullPath: '/candidates/signup'
      preLoaderRoute: typeof CandidatesSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/signin': {
      id: '/candidates/signin'
      path: '/candidates/signin'
      fullPath: '/candidates/signin'
      preLoaderRoute: typeof CandidatesSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/dashboard': {
      id: '/candidates/dashboard'
      path: '/candidates/dashboard'
      fullPath: '/candidates/dashboard'
      preLoaderRoute: typeof CandidatesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JobsRoute: JobsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  CandidatesDashboardRoute: CandidatesDashboardRoute,
  CandidatesSigninRoute: CandidatesSigninRoute,
  CandidatesSignupRoute: CandidatesSignupRoute,
  EmployersDashboardRoute: EmployersDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
